/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.offertelowcost.gui;

import java.io.File;
import java.io.FileInputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import net.bican.wordpress.FilterPost;
import net.bican.wordpress.MediaItem;
import net.bican.wordpress.MediaItemUploadResult;
import net.bican.wordpress.Post;
import net.bican.wordpress.Term;
import net.bican.wordpress.Wordpress;
import net.bican.wordpress.exceptions.InsufficientRightsException;
import net.bican.wordpress.exceptions.ObjectNotFoundException;
import org.apache.commons.io.FileUtils;
import redstone.xmlrpc.XmlRpcFault;

/**
 *
 * @author felefant
 */
public class PostManager extends javax.swing.JFrame {

    Wordpress wp;

    /**
     * Creates new form PostManager
     *
     * @param wp
     * @param xmlRpcUrl
     */
    public PostManager(Wordpress wp, String xmlRpcUrl) {
        try {
            initComponents();

            this.wp = wp;

            List<Term> categorie = wp.getTerms("category");

            DefaultComboBoxModel model = new DefaultComboBoxModel();

            xmlRPCTextField.setText(xmlRpcUrl);

            for (Term t : categorie) {
//                System.err.println(t.getName());

                ComboBoxItem cbi = new ComboBoxItem(t);
                model.addElement(cbi);
            }
            jComboBox1.setModel(model);

            List<MediaItem> medias = wp.getMediaLibrary();

            for (MediaItem m : medias) {
                System.err.println("######");
                System.err.println(m);
            }
        } catch (Exception ex) {
            Logger.getLogger(PostManager.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        xmlRPCTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wordpress Post Manager");

        jLabel1.setText("Post content");

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.setText("<h2>Articolo di test</h2>\n");
        jScrollPane1.setViewportView(jTextArea);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("Titolo di test");

        jLabel2.setText("Post Title");

        jTextField2.setText("http://ecx.images-amazon.com/images/I/71VImzUnFTL._UX385_.jpg");

        jLabel3.setText("Image URL");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elettronica", "Informatica", "Sport", "Casa" }));

        jLabel4.setText("Post Category");

        jLabel5.setText("URL XML-RPC");

        xmlRPCTextField.setText("jTextField3");
        xmlRPCTextField.setEnabled(false);

        jMenu1.setText("File");

        jMenuItem1.setText("Delete all posts");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(xmlRPCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xmlRPCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            URL url = new URL("http://www.statimweb.it/images/75mskniks662/Donna-Scarpe-Nike-Air-Max-2015-Nere-Verde-Blu-Bianche-4Wub4qz.jpg");
            String title = jTextField1.getText();
            String content = jTextArea.getText();

            final Post recentPost = new Post();
            recentPost.setPost_title(title);
            recentPost.setPost_content(content);
            recentPost.setPost_status("publish");

            List<Term> listT = new ArrayList<>();
            listT.add(((ComboBoxItem) jComboBox1.getModel().getSelectedItem()).getTerm());
            recentPost.setTerms(listT);
            
            MediaItem media = new MediaItem();
//            media.setLink(url.toString());
            media.setAttachment_id(151);
//            media.setLink("http://www.offertelowcost.net/wp-content/uploads/2016/03/hoodie_6_front-600x600.jpg");
            
            recentPost.setPost_thumbnail(media);
            
            final Integer result = wp.newPost(recentPost);
            System.out.println("#### New post page id: " + result + " created!");

//
//            File file = new File("downloaded.jpg");
//            FileUtils.copyURLToFile(url, file);
//            try (FileInputStream fis = new FileInputStream(file)) {
//                final MediaItemUploadResult result2 = wp.uploadFile(fis, file.getName(), false);
//                if (result2 != null) {
//                    System.out.println("#### New file: " + result2 + " uploaded!");
//                }
//            }

        } catch (Exception ex) {
            Logger.getLogger(PostManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        try {
            FilterPost filter = new FilterPost();
            List<Post> recentPosts = wp.getPosts(filter);

            if (recentPosts.isEmpty()) {
                System.out.println("non ci sono post");
            } else {

                System.out.println("Sto per rimuovere tutti i posts....");
                System.out.println("=============");
                for (final Post page : recentPosts) {
                    System.out.println("sto per rimuovere il post con nome " + page.getPost_name());
                    int id = page.getPost_id();
                    wp.deletePost(id);
                    System.out.println("il post con id " + id + " è stato rimosso...");
                }
            }
        } catch (XmlRpcFault ex) {
            Logger.getLogger(PostManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InsufficientRightsException ex) {
            Logger.getLogger(PostManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ObjectNotFoundException ex) {
            Logger.getLogger(PostManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField xmlRPCTextField;
    // End of variables declaration//GEN-END:variables
}
